"""Add maquina_id to apontamentos

Revision ID: 00c97947538f
Revises: 
Create Date: 2025-06-10 17:04:54.456182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c97947538f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apontamentos', sa.Column('maquina_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apontamentos', 'maquinas', ['maquina_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apontamentos', type_='foreignkey')
    op.drop_column('apontamentos', 'maquina_id')
    # ### end Alembic commands ###
